spring.application.name=spring-security-demo

spring.security.user.name = star
spring.security.user.password = 1234

server.servlet.session.cookie.same-site = strict

spring.datasourse.url = jdbc:postgresql://localhost:5432/star
spring.datasourse.username = hardivirani
#spring.datasourse.password
